spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/geocoding?profileSQL=true"
    username: root
    password:
  jpa:
    database: MYSQL
  mvc.view:
    prefix: /WEB-INF/jsp/
    suffix: .jsp